# Panel Detection Configuration
# All parameters for panel detection algorithms

# Core detection parameters
detection:
  min_panel_height: 200          # Minimum height for a valid panel (pixels)
  min_gap_height: 50              # Minimum gap size to consider splitting (pixels)
  white_threshold: 245            # Brightness threshold for "white" rows (0-255)
  padding: 5                      # Pixels to add around detected panels
  max_panel_height: 3000          # Force split if panel exceeds this height

  # Overlap strategy (prevents content loss at boundaries)
  overlap:
    enabled: true
    margin_top: 50                # Pixels to extend upward into previous panel
    margin_bottom: 50             # Pixels to extend downward into next panel
    adaptive: true                # Adjust overlap based on gap confidence

  # Edge detection parameters (for validation)
  edge_detection:
    enabled: true
    canny_low: 30                 # Lower threshold for Canny edge detection
    canny_high: 100               # Upper threshold for Canny edge detection
    min_edge_density: 50          # Edge pixels per row to consider "content"
    content_buffer: 100           # Buffer zone around split points to verify empty

# Detection modes (different aggressiveness levels)
modes:
  strict:
    min_gap_height: 600           # Only split on large scene transitions
    white_threshold: 250
    description: "Conservative splitting - only clear scene changes"
    use_case: "Episodes with obvious transitions"

  standard:
    min_gap_height: 200           # WEBTOON recommended spacing
    white_threshold: 245
    description: "Balanced approach with edge validation"
    use_case: "Most episodes (default)"

  aggressive:
    min_gap_height: 50            # Split on any detectable gap
    white_threshold: 240
    description: "Maximum splitting for dense layouts"
    use_case: "Episodes with minimal spacing"

# Fallback strategy when no gaps detected
fallback:
  enabled: true
  chunk_size: 2000                # Default chunk size if no gaps found
  search_range: 400               # Range around target split to find best point
  prefer_brightness: true         # Choose brightest row in search range

# Quality validation
validation:
  enabled: true
  min_panels: 1                   # Minimum panels expected per episode
  max_panels: 200                 # Maximum panels expected per episode
  check_overlap: true             # Verify panels don't incorrectly overlap
  check_gaps: true                # Verify gaps between panels are reasonable

# Performance settings
performance:
  enable_caching: true
  cache_size_mb: 500              # Max memory for image cache
  parallel_processing: false      # Enable multiprocessing (experimental)
  num_workers: 4                  # Number of worker processes
